from telebot import types
import telebot

wayMenu = telebot.types.ReplyKeyboardMarkup(resize_keyboard=True)
btnTeacher = telebot.types.KeyboardButton('Учитель')
btnParent = telebot.types.KeyboardButton('Родитель')
wayMenu.add(btnTeacher, btnParent)

classsMenu = telebot.types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = telebot.types.KeyboardButton('1')
btn2 = telebot.types.KeyboardButton('2')
btn3 = telebot.types.KeyboardButton('3')
btn4 = telebot.types.KeyboardButton('4')
btn5 = telebot.types.KeyboardButton('5')
btn6 = telebot.types.KeyboardButton('6')
btn7 = telebot.types.KeyboardButton('7')
btn8 = telebot.types.KeyboardButton('8')
btn9 = telebot.types.KeyboardButton('9')
btn10 = telebot.types.KeyboardButton('10')
btn11 = telebot.types.KeyboardButton('11')
classsMenu.add(btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btn10, btn11)

letterMenu = telebot.types.ReplyKeyboardMarkup(resize_keyboard=True)
btnA = telebot.types.KeyboardButton('А')
btnB = telebot.types.KeyboardButton('Б')
btnC = telebot.types.KeyboardButton('В')
letterMenu.add(btnA, btnB, btnC)

subjectMenu = telebot.types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1111 = telebot.types.KeyboardButton('АЛГЕБРА')
btn22 = telebot.types.KeyboardButton('РУССКИЙ ЯЗЫК')
btn33 = telebot.types.KeyboardButton('ГЕОМЕТРИЯ')
btn44 = telebot.types.KeyboardButton('ФИЗИКА')
btn55 = telebot.types.KeyboardButton('ЛИТЕРАТУРА')
btn66 = telebot.types.KeyboardButton('БИОЛОГИЯ')
btn77 = telebot.types.KeyboardButton('ОБЩЕСТВОЗНАНИЕ')
btn88 = telebot.types.KeyboardButton('ИСТОРИЯ')
btn99 = telebot.types.KeyboardButton('АНГЛИЙСКИЙ ЯЗЫК')
btn100 = telebot.types.KeyboardButton('ХИМИЯ')
btn111 = telebot.types.KeyboardButton('ГЕОГРАФИЯ')
subjectMenu.add(btn1111, btn22, btn33, btn44, btn55, btn66, btn77, btn88, btn99, btn100, btn111)

findMenu = telebot.types.ReplyKeyboardMarkup(resize_keyboard=True)
btn = telebot.types.KeyboardButton('Поиск')
btn0 = telebot.types.KeyboardButton('Помощь')
btn00 = telebot.types.KeyboardButton('Чат класса')
findMenu.add(btn, btn0, btn00)

checkMenu = telebot.types.ReplyKeyboardMarkup(resize_keyboard=True)
btn_done = telebot.types.KeyboardButton('☑️')
checkMenu.add(btn_done)

ansMenu = telebot.types.ReplyKeyboardMarkup(resize_keyboard=True)
btn_yes = telebot.types.KeyboardButton('Да')
btn_no = telebot.types.KeyboardButton('Нет')
ansMenu.add(btn_yes, btn_no)
